# Generated by Django 5.2.4 on 2025-08-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otpattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpattempt',
            name='code_entered',
            field=models.CharField(default='000000', max_length=6),
            preserve_default=False,
        ),
    ]
