# Generated by Django 5.2.4 on 2025-08-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_otpattempt_code_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpattempt',
            name='code_entered',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='users_otp_user_id_eb7a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='otpattempt',
            index=models.Index(fields=['user', 'success'], name='users_otpat_user_id_f024f8_idx'),
        ),
    ]
