# Generated by Django 5.2.4 on 2025-08-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Vendor API product code', max_length=50)),
                ('product_type', models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data Bundle')], max_length=10)),
                ('provider', models.CharField(choices=[('mtn', 'MTN'), ('glo', 'Glo'), ('airtel', 'Airtel'), ('9mobile', '9mobile')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='E.g. 100 naira / 500 MB', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='What agent pays per unit', max_digits=10)),
            ],
            options={
                'ordering': ['provider', 'product_type', 'value'],
            },
        ),
    ]
