# Generated by Django 5.2.4 on 2025-08-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_remove_transaction_type_transaction_bundle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup', 'Top-up'), ('withdraw', 'Withdraw'), ('purchase', 'Purchase')], default='topup', max_length=10),
        ),
    ]
