# Generated by Django 5.2.4 on 2025-08-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(blank=True, help_text='Virtual NUBAN-style account number', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bank_name',
            field=models.CharField(default='Moniepoint', help_text='Name of the provider/bank', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup', 'Top-up'), ('withdraw', 'Withdraw'), ('purchase', 'Purchase')], default='topup', help_text='Type of transaction', max_length=10),
        ),
    ]
