# Generated by Django 5.2.4 on 2025-08-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_wallet_account_number_wallet_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, help_text='Optional transaction note', null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bank_name',
            field=models.CharField(default='Moniepoint', help_text='Provider or bank name', max_length=50),
        ),
    ]
